apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-kustomize-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/cioban/argocd-app1.git"
    targetRevision: "main"
    path: "kustomize/overlays/prod"
  destination:
    # Deploy into the in-cluster Kubernetes API (default ArgoCD cluster)
    server: "https://kubernetes.default.svc"
    namespace: app1-kustomize-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true        # remove resources that are no longer declared in Git
      selfHeal: true     # revert manual changes
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
