apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: nginx
          # using a small stable nginx image
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            # Mount the single key 'index.html' from the ConfigMap over the default index file
            - name: index-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
              readOnly: true
      volumes:
        - name: index-volume
          configMap:
            name: nginx-index
            # only expose the index.html key into the volume
            items:
              - key: index.html
                path: index.html
